repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5120']  # 5MB
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-toml
  - repo: https://github.com/qiaojunfeng/pre-commit-julia-format
    rev: v0.1.1
    hooks:
    - id: julia-format
