name = "AtomicPotentials"
uuid = "0015ad10-6e07-47eb-baf7-dbb079bee869"
authors = ["Austin Zadoks <austin.zadoks@protonmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
