name = "AtomicPotentials"
uuid = "0015ad10-6e07-47eb-baf7-dbb079bee869"
authors = ["Austin Zadoks <austin.zadoks@protonmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
