name = "AtomicPotentials"
uuid = "0015ad10-6e07-47eb-baf7-dbb079bee869"
authors = ["Austin Zadoks <austin.zadoks@protonmail.com>"]
version = "0.1.0"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
